/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PhirepassSftpClient {
        /**
          * @default 'Client'
         */
        "description": string;
        "maximize": () => Promise<void>;
        "minimize": () => Promise<void>;
        /**
          * @default 'SFTP'
         */
        "name": string;
        /**
          * @default false
         */
        "showLoginScreen": boolean;
    }
    interface PhirepassTerminal {
        /**
          * @default false
         */
        "allowInsecure": boolean;
        /**
          * @default 30_000
         */
        "heartbeatInterval": number;
        "nodeId": string;
        /**
          * @default "phirepass.com"
         */
        "serverHost": string;
        "serverId"?: string;
        /**
          * @default 443
         */
        "serverPort": number;
        /**
          * @default {         // Terminal identification         termName: 'xterm-256color',          // Rendering         rendererType: 'canvas', // Better performance         allowTransparency: false,          fontFamily:             '"Berkeley Mono", "Fira Code", "SFMono-Regular", Menlo, monospace',         fontSize: 12,         // fontWeight: 'normal',         // fontWeightBold: 'bold',         letterSpacing: 0,         lineHeight: 1.0,          allowProposedApi: true, // needed for bracketed paste          // Cursor         cursorBlink: true,         // cursorStyle: 'block',         cursorWidth: 1,          // Colors         theme: {             background: "#0b1021",             foreground: "#e2e8f0",             cursor: "#67e8f9",         },          // Scrolling         scrollback: 10000,         fastScrollModifier: 'shift',         fastScrollSensitivity: 5,          // Behavior         bellStyle: 'sound', // or 'none' if you prefer         convertEol: false, // true to treat \n as \r\n         disableStdin: false,          // Selection         rightClickSelectsWord: true,          // Performance         drawBoldTextInBrightColors: true,         minimumContrastRatio: 1,          // Advanced         windowsMode: false, // Important for Linux         macOptionIsMeta: false,         altClickMovesCursor: true     }
         */
        "terminalOptions": { termName: string; rendererType: string; allowTransparency: boolean; fontFamily: string; fontSize: number; letterSpacing: number; lineHeight: number; allowProposedApi: boolean; cursorBlink: boolean; cursorWidth: number; theme: { background: string; foreground: string; cursor: string; }; scrollback: number; fastScrollModifier: string; fastScrollSensitivity: number; bellStyle: string; convertEol: boolean; disableStdin: boolean; rightClickSelectsWord: boolean; drawBoldTextInBrightColors: boolean; minimumContrastRatio: number; windowsMode: boolean; macOptionIsMeta: boolean; altClickMovesCursor: boolean; };
        "token": string;
    }
}
export interface PhirepassSftpClientCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPhirepassSftpClientElement;
}
export interface PhirepassTerminalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPhirepassTerminalElement;
}
declare global {
    interface HTMLPhirepassSftpClientElementEventMap {
        "maximize": any;
    }
    interface HTMLPhirepassSftpClientElement extends Components.PhirepassSftpClient, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPhirepassSftpClientElementEventMap>(type: K, listener: (this: HTMLPhirepassSftpClientElement, ev: PhirepassSftpClientCustomEvent<HTMLPhirepassSftpClientElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPhirepassSftpClientElementEventMap>(type: K, listener: (this: HTMLPhirepassSftpClientElement, ev: PhirepassSftpClientCustomEvent<HTMLPhirepassSftpClientElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPhirepassSftpClientElement: {
        prototype: HTMLPhirepassSftpClientElement;
        new (): HTMLPhirepassSftpClientElement;
    };
    interface HTMLPhirepassTerminalElementEventMap {
        "connectionStateChanged": [ConnectionState, unknown?];
    }
    interface HTMLPhirepassTerminalElement extends Components.PhirepassTerminal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPhirepassTerminalElementEventMap>(type: K, listener: (this: HTMLPhirepassTerminalElement, ev: PhirepassTerminalCustomEvent<HTMLPhirepassTerminalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPhirepassTerminalElementEventMap>(type: K, listener: (this: HTMLPhirepassTerminalElement, ev: PhirepassTerminalCustomEvent<HTMLPhirepassTerminalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPhirepassTerminalElement: {
        prototype: HTMLPhirepassTerminalElement;
        new (): HTMLPhirepassTerminalElement;
    };
    interface HTMLElementTagNameMap {
        "phirepass-sftp-client": HTMLPhirepassSftpClientElement;
        "phirepass-terminal": HTMLPhirepassTerminalElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface PhirepassSftpClient {
        /**
          * @default 'Client'
         */
        "description"?: string;
        /**
          * @default 'SFTP'
         */
        "name"?: string;
        "onMaximize"?: (event: PhirepassSftpClientCustomEvent<any>) => void;
        /**
          * @default false
         */
        "showLoginScreen"?: boolean;
    }
    interface PhirepassTerminal {
        /**
          * @default false
         */
        "allowInsecure"?: boolean;
        /**
          * @default 30_000
         */
        "heartbeatInterval"?: number;
        "nodeId": string;
        "onConnectionStateChanged"?: (event: PhirepassTerminalCustomEvent<[ConnectionState, unknown?]>) => void;
        /**
          * @default "phirepass.com"
         */
        "serverHost"?: string;
        "serverId"?: string;
        /**
          * @default 443
         */
        "serverPort"?: number;
        /**
          * @default {         // Terminal identification         termName: 'xterm-256color',          // Rendering         rendererType: 'canvas', // Better performance         allowTransparency: false,          fontFamily:             '"Berkeley Mono", "Fira Code", "SFMono-Regular", Menlo, monospace',         fontSize: 12,         // fontWeight: 'normal',         // fontWeightBold: 'bold',         letterSpacing: 0,         lineHeight: 1.0,          allowProposedApi: true, // needed for bracketed paste          // Cursor         cursorBlink: true,         // cursorStyle: 'block',         cursorWidth: 1,          // Colors         theme: {             background: "#0b1021",             foreground: "#e2e8f0",             cursor: "#67e8f9",         },          // Scrolling         scrollback: 10000,         fastScrollModifier: 'shift',         fastScrollSensitivity: 5,          // Behavior         bellStyle: 'sound', // or 'none' if you prefer         convertEol: false, // true to treat \n as \r\n         disableStdin: false,          // Selection         rightClickSelectsWord: true,          // Performance         drawBoldTextInBrightColors: true,         minimumContrastRatio: 1,          // Advanced         windowsMode: false, // Important for Linux         macOptionIsMeta: false,         altClickMovesCursor: true     }
         */
        "terminalOptions"?: { termName: string; rendererType: string; allowTransparency: boolean; fontFamily: string; fontSize: number; letterSpacing: number; lineHeight: number; allowProposedApi: boolean; cursorBlink: boolean; cursorWidth: number; theme: { background: string; foreground: string; cursor: string; }; scrollback: number; fastScrollModifier: string; fastScrollSensitivity: number; bellStyle: string; convertEol: boolean; disableStdin: boolean; rightClickSelectsWord: boolean; drawBoldTextInBrightColors: boolean; minimumContrastRatio: number; windowsMode: boolean; macOptionIsMeta: boolean; altClickMovesCursor: boolean; };
        "token": string;
    }

    interface PhirepassSftpClientAttributes {
        "name": string;
        "description": string;
        "showLoginScreen": boolean;
    }
    interface PhirepassTerminalAttributes {
        "serverHost": string;
        "serverPort": number;
        "allowInsecure": boolean;
        "heartbeatInterval": number;
        "nodeId": string;
        "token": string;
        "serverId": string;
    }

    interface IntrinsicElements {
        "phirepass-sftp-client": Omit<PhirepassSftpClient, keyof PhirepassSftpClientAttributes> & { [K in keyof PhirepassSftpClient & keyof PhirepassSftpClientAttributes]?: PhirepassSftpClient[K] } & { [K in keyof PhirepassSftpClient & keyof PhirepassSftpClientAttributes as `attr:${K}`]?: PhirepassSftpClientAttributes[K] } & { [K in keyof PhirepassSftpClient & keyof PhirepassSftpClientAttributes as `prop:${K}`]?: PhirepassSftpClient[K] };
        "phirepass-terminal": Omit<PhirepassTerminal, keyof PhirepassTerminalAttributes> & { [K in keyof PhirepassTerminal & keyof PhirepassTerminalAttributes]?: PhirepassTerminal[K] } & { [K in keyof PhirepassTerminal & keyof PhirepassTerminalAttributes as `attr:${K}`]?: PhirepassTerminalAttributes[K] } & { [K in keyof PhirepassTerminal & keyof PhirepassTerminalAttributes as `prop:${K}`]?: PhirepassTerminal[K] } & OneOf<"nodeId", PhirepassTerminal["nodeId"], PhirepassTerminalAttributes["nodeId"]> & OneOf<"token", PhirepassTerminal["token"], PhirepassTerminalAttributes["token"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "phirepass-sftp-client": LocalJSX.IntrinsicElements["phirepass-sftp-client"] & JSXBase.HTMLAttributes<HTMLPhirepassSftpClientElement>;
            "phirepass-terminal": LocalJSX.IntrinsicElements["phirepass-terminal"] & JSXBase.HTMLAttributes<HTMLPhirepassTerminalElement>;
        }
    }
}
