/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ConnectionState } from "./common/protocol";
export { ConnectionState } from "./common/protocol";
export namespace Components {
    /**
     * Remote desktop over RDP.
     * Unlike the terminal and SFTP widgets this one does not pipe protocol bytes
     * through the phirepass channel. The channel is used only to authorise the
     * session; the actual RDP stream runs on a second WebSocket opened by IronRDP's
     * own client, because that client speaks RDCleanPath and can set neither
     * headers nor a subprotocol on the socket it opens. See `RDP.md` in
     * `phirepass-rs` for why the session is split across two sockets.
     */
    interface PhirepassRdp {
        /**
          * @default false
         */
        "allowInsecure": boolean;
        /**
          * While the widget is fullscreen, take the keys the browser normally keeps for itself (Ctrl+W, Ctrl+T, Alt+Tab, F11) and send them to the remote host instead. Escape is taken too, so leaving fullscreen becomes a press-and-hold.  Ordinary keys do not depend on this — they are forwarded whenever the desktop has focus.
          * @default true
         */
        "captureKeyboard": boolean;
        /**
          * Share the clipboard with the remote host in both directions.  On is the client's own default and needs nothing from us, so this exists to turn it **off**: a deployment that treats copy-out as exfiltration can take the clipboard away without giving up the session. Clipboard access additionally needs a secure context — over plain HTTP the browser refuses it whatever this says, and the client's warning is logged.
          * @default true
         */
        "clipboard": boolean;
        /**
          * What to name the host in the CredSSP service principal (`TERMSRV/...`).  The agent dials whatever the node's service settings say, so this is never used for routing. It matters only because some hosts check the SPN, and the browser has no other way to learn the host's real address.
         */
        "destination"?: string;
        /**
          * Ask the remote host to change its resolution to match the widget whenever the widget is resized, so the desktop is rendered at native size rather than scaled.  Turning this on is what registers the display-control extension, since the channel it opens is negotiated at connect time and never afterwards. The host still has the last word: one that does not offer the channel keeps the resolution it started with, which `scale` then fits into the widget, as before.
          * @default true
         */
        "dynamicResize": boolean;
        /**
          * Directs keystrokes at the remote desktop without waiting for a click.
         */
        "focusDesktop": () => Promise<void>;
        /**
          * @default 30_000
         */
        "heartbeatInterval": number;
        /**
          * Whether the browser can hand over its reserved keys at all.
         */
        "keyboardLockSupported": () => Promise<boolean>;
        "nodeId": string;
        "password"?: string;
        /**
          * `fit` scales the desktop to the widget, `real` keeps 1:1 pixels.
          * @default 'fit'
         */
        "scale": 'fit' | 'full' | 'real';
        /**
          * Sends Ctrl+Alt+Del to the remote host.  The host has to be told, because pressing it never reaches us: Ctrl+Alt+Del is a secure attention sequence the operating system takes before any browser sees it, and `captureKeyboard` cannot claim it either. Yet it is how a Windows session is unlocked and how the login screen is reached, so without this a locked desktop is a dead end.  Answers whether it was sent — there is no session to send it to until the client has connected.
         */
        "sendCtrlAltDel": () => Promise<boolean>;
        /**
          * Sends the Meta (Windows/Command) key to the remote host, which opens the Start menu. Outside fullscreen the browser and the desktop environment take this key first, so like Ctrl+Alt+Del it has to be sendable directly.
         */
        "sendMetaKey": () => Promise<boolean>;
        /**
          * @default "phirepass.com"
         */
        "serverHost": string;
        "serverId"?: string;
        /**
          * @default 443
         */
        "serverPort": number;
        "serviceId": string;
        /**
          * Puts the widget in and out of fullscreen, returning the state it settled in. Fullscreen is also what makes `captureKeyboard` possible, so a host app wanting the browser's own shortcuts to reach the remote desktop has to come through here.
         */
        "toggleFullscreen": () => Promise<boolean>;
        "token": string;
        /**
          * Credentials for the remote host. When either is missing the widget prompts for both.  They serve two purposes at once: the agent checks them before it authorises the tunnel, and the browser uses them for CredSSP. The agent never logs in with them — it discards them once the tunnel is authorised.
         */
        "username"?: string;
    }
    interface PhirepassSftpClient {
        /**
          * @default false
         */
        "allowInsecure": boolean;
        /**
          * @default 'Client'
         */
        "description": string;
        /**
          * @default 30_000
         */
        "heartbeatInterval": number;
        /**
          * @default false
         */
        "hideHeader": boolean;
        "maximize": () => Promise<void>;
        "minimize": () => Promise<void>;
        /**
          * @default 'SFTP'
         */
        "name": string;
        "nodeId": string;
        /**
          * @default "phirepass.com"
         */
        "serverHost": string;
        "serverId"?: string;
        /**
          * @default 443
         */
        "serverPort": number;
        "serviceId": string;
        "token": string;
    }
    interface PhirepassTerminal {
        /**
          * @default false
         */
        "allowInsecure": boolean;
        /**
          * @default 30_000
         */
        "heartbeatInterval": number;
        /**
          * Whether to draw the on-screen key bar.  `auto` shows it wherever the pointer is coarse, which is the whole of the decision on a phone and none of it on a desktop — so it is answered in CSS (`@media (pointer: coarse)`) rather than by sniffing the user agent here. `on` and `off` exist because an embedder may know better: a tablet with a keyboard case reports a coarse pointer and does not need this.
          * @default 'auto'
         */
        "keyBar": 'auto' | 'on' | 'off';
        "nodeId": string;
        /**
          * @default "phirepass.com"
         */
        "serverHost": string;
        "serverId"?: string;
        /**
          * @default 443
         */
        "serverPort": number;
        "serviceId": string;
        /**
          * @default {         // Terminal identification         termName: 'xterm-256color',          // Rendering         rendererType: 'canvas', // Better performance         allowTransparency: false,          fontFamily:             '"Berkeley Mono", "Fira Code", "SFMono-Regular", Menlo, monospace',         fontSize: 12,         // fontWeight: 'normal',         // fontWeightBold: 'bold',         letterSpacing: 0,         lineHeight: 1.0,          allowProposedApi: true, // needed for bracketed paste          // Cursor         cursorBlink: true,         // cursorStyle: 'block',         cursorWidth: 1,          // Colors         theme: {             background: "#0b1021",             foreground: "#e2e8f0",             cursor: "#67e8f9",         },          // Scrolling         scrollback: 10000,         fastScrollModifier: 'shift',         fastScrollSensitivity: 5,          // Behavior         bellStyle: 'sound', // or 'none' if you prefer         convertEol: false, // true to treat \n as \r\n         disableStdin: false,          // Selection         rightClickSelectsWord: true,          // Performance         drawBoldTextInBrightColors: true,         minimumContrastRatio: 1,          // Advanced         windowsMode: false, // Important for Linux         macOptionIsMeta: false,         altClickMovesCursor: true     }
         */
        "terminalOptions": { termName: string; rendererType: string; allowTransparency: boolean; fontFamily: string; fontSize: number; letterSpacing: number; lineHeight: number; allowProposedApi: boolean; cursorBlink: boolean; cursorWidth: number; theme: { background: string; foreground: string; cursor: string; }; scrollback: number; fastScrollModifier: string; fastScrollSensitivity: number; bellStyle: string; convertEol: boolean; disableStdin: boolean; rightClickSelectsWord: boolean; drawBoldTextInBrightColors: boolean; minimumContrastRatio: number; windowsMode: boolean; macOptionIsMeta: boolean; altClickMovesCursor: boolean; };
        "token": string;
    }
}
export interface PhirepassRdpCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPhirepassRdpElement;
}
export interface PhirepassSftpClientCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPhirepassSftpClientElement;
}
export interface PhirepassTerminalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPhirepassTerminalElement;
}
declare global {
    interface HTMLPhirepassRdpElementEventMap {
        "connectionStateChanged": [ConnectionState, unknown?];
    }
    /**
     * Remote desktop over RDP.
     * Unlike the terminal and SFTP widgets this one does not pipe protocol bytes
     * through the phirepass channel. The channel is used only to authorise the
     * session; the actual RDP stream runs on a second WebSocket opened by IronRDP's
     * own client, because that client speaks RDCleanPath and can set neither
     * headers nor a subprotocol on the socket it opens. See `RDP.md` in
     * `phirepass-rs` for why the session is split across two sockets.
     */
    interface HTMLPhirepassRdpElement extends Components.PhirepassRdp, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPhirepassRdpElementEventMap>(type: K, listener: (this: HTMLPhirepassRdpElement, ev: PhirepassRdpCustomEvent<HTMLPhirepassRdpElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPhirepassRdpElementEventMap>(type: K, listener: (this: HTMLPhirepassRdpElement, ev: PhirepassRdpCustomEvent<HTMLPhirepassRdpElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPhirepassRdpElement: {
        prototype: HTMLPhirepassRdpElement;
        new (): HTMLPhirepassRdpElement;
    };
    interface HTMLPhirepassSftpClientElementEventMap {
        "maximize": any;
        "connectionStateChanged": [ConnectionState, unknown?];
    }
    interface HTMLPhirepassSftpClientElement extends Components.PhirepassSftpClient, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPhirepassSftpClientElementEventMap>(type: K, listener: (this: HTMLPhirepassSftpClientElement, ev: PhirepassSftpClientCustomEvent<HTMLPhirepassSftpClientElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPhirepassSftpClientElementEventMap>(type: K, listener: (this: HTMLPhirepassSftpClientElement, ev: PhirepassSftpClientCustomEvent<HTMLPhirepassSftpClientElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPhirepassSftpClientElement: {
        prototype: HTMLPhirepassSftpClientElement;
        new (): HTMLPhirepassSftpClientElement;
    };
    interface HTMLPhirepassTerminalElementEventMap {
        "connectionStateChanged": [ConnectionState, unknown?];
    }
    interface HTMLPhirepassTerminalElement extends Components.PhirepassTerminal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPhirepassTerminalElementEventMap>(type: K, listener: (this: HTMLPhirepassTerminalElement, ev: PhirepassTerminalCustomEvent<HTMLPhirepassTerminalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPhirepassTerminalElementEventMap>(type: K, listener: (this: HTMLPhirepassTerminalElement, ev: PhirepassTerminalCustomEvent<HTMLPhirepassTerminalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPhirepassTerminalElement: {
        prototype: HTMLPhirepassTerminalElement;
        new (): HTMLPhirepassTerminalElement;
    };
    interface HTMLElementTagNameMap {
        "phirepass-rdp": HTMLPhirepassRdpElement;
        "phirepass-sftp-client": HTMLPhirepassSftpClientElement;
        "phirepass-terminal": HTMLPhirepassTerminalElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    /**
     * Remote desktop over RDP.
     * Unlike the terminal and SFTP widgets this one does not pipe protocol bytes
     * through the phirepass channel. The channel is used only to authorise the
     * session; the actual RDP stream runs on a second WebSocket opened by IronRDP's
     * own client, because that client speaks RDCleanPath and can set neither
     * headers nor a subprotocol on the socket it opens. See `RDP.md` in
     * `phirepass-rs` for why the session is split across two sockets.
     */
    interface PhirepassRdp {
        /**
          * @default false
         */
        "allowInsecure"?: boolean;
        /**
          * While the widget is fullscreen, take the keys the browser normally keeps for itself (Ctrl+W, Ctrl+T, Alt+Tab, F11) and send them to the remote host instead. Escape is taken too, so leaving fullscreen becomes a press-and-hold.  Ordinary keys do not depend on this — they are forwarded whenever the desktop has focus.
          * @default true
         */
        "captureKeyboard"?: boolean;
        /**
          * Share the clipboard with the remote host in both directions.  On is the client's own default and needs nothing from us, so this exists to turn it **off**: a deployment that treats copy-out as exfiltration can take the clipboard away without giving up the session. Clipboard access additionally needs a secure context — over plain HTTP the browser refuses it whatever this says, and the client's warning is logged.
          * @default true
         */
        "clipboard"?: boolean;
        /**
          * What to name the host in the CredSSP service principal (`TERMSRV/...`).  The agent dials whatever the node's service settings say, so this is never used for routing. It matters only because some hosts check the SPN, and the browser has no other way to learn the host's real address.
         */
        "destination"?: string;
        /**
          * Ask the remote host to change its resolution to match the widget whenever the widget is resized, so the desktop is rendered at native size rather than scaled.  Turning this on is what registers the display-control extension, since the channel it opens is negotiated at connect time and never afterwards. The host still has the last word: one that does not offer the channel keeps the resolution it started with, which `scale` then fits into the widget, as before.
          * @default true
         */
        "dynamicResize"?: boolean;
        /**
          * @default 30_000
         */
        "heartbeatInterval"?: number;
        "nodeId": string;
        "onConnectionStateChanged"?: (event: PhirepassRdpCustomEvent<[ConnectionState, unknown?]>) => void;
        "password"?: string;
        /**
          * `fit` scales the desktop to the widget, `real` keeps 1:1 pixels.
          * @default 'fit'
         */
        "scale"?: 'fit' | 'full' | 'real';
        /**
          * @default "phirepass.com"
         */
        "serverHost"?: string;
        "serverId"?: string;
        /**
          * @default 443
         */
        "serverPort"?: number;
        "serviceId": string;
        "token": string;
        /**
          * Credentials for the remote host. When either is missing the widget prompts for both.  They serve two purposes at once: the agent checks them before it authorises the tunnel, and the browser uses them for CredSSP. The agent never logs in with them — it discards them once the tunnel is authorised.
         */
        "username"?: string;
    }
    interface PhirepassSftpClient {
        /**
          * @default false
         */
        "allowInsecure"?: boolean;
        /**
          * @default 'Client'
         */
        "description"?: string;
        /**
          * @default 30_000
         */
        "heartbeatInterval"?: number;
        /**
          * @default false
         */
        "hideHeader"?: boolean;
        /**
          * @default 'SFTP'
         */
        "name"?: string;
        "nodeId": string;
        "onConnectionStateChanged"?: (event: PhirepassSftpClientCustomEvent<[ConnectionState, unknown?]>) => void;
        "onMaximize"?: (event: PhirepassSftpClientCustomEvent<any>) => void;
        /**
          * @default "phirepass.com"
         */
        "serverHost"?: string;
        "serverId"?: string;
        /**
          * @default 443
         */
        "serverPort"?: number;
        "serviceId": string;
        "token": string;
    }
    interface PhirepassTerminal {
        /**
          * @default false
         */
        "allowInsecure"?: boolean;
        /**
          * @default 30_000
         */
        "heartbeatInterval"?: number;
        /**
          * Whether to draw the on-screen key bar.  `auto` shows it wherever the pointer is coarse, which is the whole of the decision on a phone and none of it on a desktop — so it is answered in CSS (`@media (pointer: coarse)`) rather than by sniffing the user agent here. `on` and `off` exist because an embedder may know better: a tablet with a keyboard case reports a coarse pointer and does not need this.
          * @default 'auto'
         */
        "keyBar"?: 'auto' | 'on' | 'off';
        "nodeId": string;
        "onConnectionStateChanged"?: (event: PhirepassTerminalCustomEvent<[ConnectionState, unknown?]>) => void;
        /**
          * @default "phirepass.com"
         */
        "serverHost"?: string;
        "serverId"?: string;
        /**
          * @default 443
         */
        "serverPort"?: number;
        "serviceId": string;
        /**
          * @default {         // Terminal identification         termName: 'xterm-256color',          // Rendering         rendererType: 'canvas', // Better performance         allowTransparency: false,          fontFamily:             '"Berkeley Mono", "Fira Code", "SFMono-Regular", Menlo, monospace',         fontSize: 12,         // fontWeight: 'normal',         // fontWeightBold: 'bold',         letterSpacing: 0,         lineHeight: 1.0,          allowProposedApi: true, // needed for bracketed paste          // Cursor         cursorBlink: true,         // cursorStyle: 'block',         cursorWidth: 1,          // Colors         theme: {             background: "#0b1021",             foreground: "#e2e8f0",             cursor: "#67e8f9",         },          // Scrolling         scrollback: 10000,         fastScrollModifier: 'shift',         fastScrollSensitivity: 5,          // Behavior         bellStyle: 'sound', // or 'none' if you prefer         convertEol: false, // true to treat \n as \r\n         disableStdin: false,          // Selection         rightClickSelectsWord: true,          // Performance         drawBoldTextInBrightColors: true,         minimumContrastRatio: 1,          // Advanced         windowsMode: false, // Important for Linux         macOptionIsMeta: false,         altClickMovesCursor: true     }
         */
        "terminalOptions"?: { termName: string; rendererType: string; allowTransparency: boolean; fontFamily: string; fontSize: number; letterSpacing: number; lineHeight: number; allowProposedApi: boolean; cursorBlink: boolean; cursorWidth: number; theme: { background: string; foreground: string; cursor: string; }; scrollback: number; fastScrollModifier: string; fastScrollSensitivity: number; bellStyle: string; convertEol: boolean; disableStdin: boolean; rightClickSelectsWord: boolean; drawBoldTextInBrightColors: boolean; minimumContrastRatio: number; windowsMode: boolean; macOptionIsMeta: boolean; altClickMovesCursor: boolean; };
        "token": string;
    }

    interface PhirepassRdpAttributes {
        "serverHost": string;
        "serverPort": number;
        "allowInsecure": boolean;
        "heartbeatInterval": number;
        "nodeId": string;
        "serviceId": string;
        "token": string;
        "username": string;
        "password": string;
        "destination": string;
        "scale": 'fit' | 'full' | 'real';
        "dynamicResize": boolean;
        "captureKeyboard": boolean;
        "clipboard": boolean;
        "serverId": string;
    }
    interface PhirepassSftpClientAttributes {
        "name": string;
        "description": string;
        "hideHeader": boolean;
        "serverHost": string;
        "serverPort": number;
        "allowInsecure": boolean;
        "heartbeatInterval": number;
        "nodeId": string;
        "serviceId": string;
        "token": string;
        "serverId": string;
    }
    interface PhirepassTerminalAttributes {
        "serverHost": string;
        "serverPort": number;
        "allowInsecure": boolean;
        "heartbeatInterval": number;
        "nodeId": string;
        "serviceId": string;
        "token": string;
        "keyBar": 'auto' | 'on' | 'off';
        "serverId": string;
    }

    interface IntrinsicElements {
        "phirepass-rdp": Omit<PhirepassRdp, keyof PhirepassRdpAttributes> & { [K in keyof PhirepassRdp & keyof PhirepassRdpAttributes]?: PhirepassRdp[K] } & { [K in keyof PhirepassRdp & keyof PhirepassRdpAttributes as `attr:${K}`]?: PhirepassRdpAttributes[K] } & { [K in keyof PhirepassRdp & keyof PhirepassRdpAttributes as `prop:${K}`]?: PhirepassRdp[K] } & OneOf<"nodeId", PhirepassRdp["nodeId"], PhirepassRdpAttributes["nodeId"]> & OneOf<"serviceId", PhirepassRdp["serviceId"], PhirepassRdpAttributes["serviceId"]> & OneOf<"token", PhirepassRdp["token"], PhirepassRdpAttributes["token"]>;
        "phirepass-sftp-client": Omit<PhirepassSftpClient, keyof PhirepassSftpClientAttributes> & { [K in keyof PhirepassSftpClient & keyof PhirepassSftpClientAttributes]?: PhirepassSftpClient[K] } & { [K in keyof PhirepassSftpClient & keyof PhirepassSftpClientAttributes as `attr:${K}`]?: PhirepassSftpClientAttributes[K] } & { [K in keyof PhirepassSftpClient & keyof PhirepassSftpClientAttributes as `prop:${K}`]?: PhirepassSftpClient[K] } & OneOf<"nodeId", PhirepassSftpClient["nodeId"], PhirepassSftpClientAttributes["nodeId"]> & OneOf<"serviceId", PhirepassSftpClient["serviceId"], PhirepassSftpClientAttributes["serviceId"]> & OneOf<"token", PhirepassSftpClient["token"], PhirepassSftpClientAttributes["token"]>;
        "phirepass-terminal": Omit<PhirepassTerminal, keyof PhirepassTerminalAttributes> & { [K in keyof PhirepassTerminal & keyof PhirepassTerminalAttributes]?: PhirepassTerminal[K] } & { [K in keyof PhirepassTerminal & keyof PhirepassTerminalAttributes as `attr:${K}`]?: PhirepassTerminalAttributes[K] } & { [K in keyof PhirepassTerminal & keyof PhirepassTerminalAttributes as `prop:${K}`]?: PhirepassTerminal[K] } & OneOf<"nodeId", PhirepassTerminal["nodeId"], PhirepassTerminalAttributes["nodeId"]> & OneOf<"serviceId", PhirepassTerminal["serviceId"], PhirepassTerminalAttributes["serviceId"]> & OneOf<"token", PhirepassTerminal["token"], PhirepassTerminalAttributes["token"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Remote desktop over RDP.
             * Unlike the terminal and SFTP widgets this one does not pipe protocol bytes
             * through the phirepass channel. The channel is used only to authorise the
             * session; the actual RDP stream runs on a second WebSocket opened by IronRDP's
             * own client, because that client speaks RDCleanPath and can set neither
             * headers nor a subprotocol on the socket it opens. See `RDP.md` in
             * `phirepass-rs` for why the session is split across two sockets.
             */
            "phirepass-rdp": LocalJSX.IntrinsicElements["phirepass-rdp"] & JSXBase.HTMLAttributes<HTMLPhirepassRdpElement>;
            "phirepass-sftp-client": LocalJSX.IntrinsicElements["phirepass-sftp-client"] & JSXBase.HTMLAttributes<HTMLPhirepassSftpClientElement>;
            "phirepass-terminal": LocalJSX.IntrinsicElements["phirepass-terminal"] & JSXBase.HTMLAttributes<HTMLPhirepassTerminalElement>;
        }
    }
}
